<a href="https://colab.research.google.com/github/Mainabryan/Data-Science-Project/blob/main/file_handling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Generate 30 random temperatures between 15°C and 35°C
temps = np.random.uniform(15, 35, 30).astype(int)

# Basic Statistics
mean_temp = np.mean(temps)
max_temp = np.max(temps)
min_temp = np.min(temps)

# Find Hottest & Coldest Days
hottest_day = np.argmax(temps) + 1
coldest_day = np.argmin(temps) + 1

# Days Above 30°C
hot_days = np.where(temps > 30)[0] + 1

# Convert to Fahrenheit
temps_fahrenheit = temps * (9/5) + 32

# Reshape Data (5x6 Matrix)
temps_matrix = temps.reshape(5, 6)

# Sort Temperatures
sorted_temps = np.sort(temps)

# Find Closest Temperature to 25°C
closest_temp_index = np.abs(temps - 25).argmin()
closest_temp = temps[closest_temp_index]

# Print Results
print("Mean Temperature:", mean_temp)
print("Max Temperature:", max_temp, "(Day", hottest_day, ")")
print("Min Temperature:", min_temp, "(Day", coldest_day, ")")
print("Days above 30°C:", hot_days)
print("Temperatures in Fahrenheit:", temps_fahrenheit)
print("Reshaped Data:\n", temps_matrix)
print("Sorted Temperatures:", sorted_temps)
print("Closest Temperature to 25°C:", closest_temp)

Mean Temperature: 24.333333333333332
Max Temperature: 33 (Day 15 )
Min Temperature: 15 (Day 29 )
Days above 30°C: [ 4  7 15 20 22 27]
Temperatures in Fahrenheit: [82.4 78.8 73.4 87.8 77.  84.2 89.6 62.6 86.  75.2 62.6 73.4 60.8 64.4
 91.4 84.2 73.4 68.  80.6 87.8 66.2 89.6 64.4 62.6 77.  80.6 91.4 62.6
 59.  77. ]
Reshaped Data:
 [[28 26 23 31 25 29]
 [32 17 30 24 17 23]
 [16 18 33 29 23 20]
 [27 31 19 32 18 17]
 [25 27 33 17 15 25]]
Sorted Temperatures: [15 16 17 17 17 17 18 18 19 20 23 23 23 24 25 25 25 26 27 27 28 29 29 30
 31 31 32 32 33 33]
Closest Temperature to 25°C: 25
